services:
  postgres:
    image: postgres:17
    container_name: postgres_db
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    networks:
      - sib_network  

volumes:
  postgres_data:  

networks:
  sib_network: 
