dbt_project:
  outputs:
    dev:
      host: clickhouse
      schema: dwh
      user: default
      password: ""
      port: 8123
      threads: 4
      type: clickhouse
  target: dev
# dbt_project: no se esta usando. Se esta usando el del dag
#   outputs:
#     dev:
#       dbname:
#       host: host.docker.internal
#       pass:
#       port: 8123 #Clickhouse port
#       # schema: dwh
#       threads: 4
#       type: clickhouse
#       user: default
#   target: dev
