dbt_project:
  outputs:
    dev:
      host: clickhouse
      schema: dwh
      user: default
      password: ""
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT') | int }}"
      threads: 4
      type: clickhouse
  target: dev
