models:
  - name: dwh.dwh_raw__stream_daily_stock_prices
    description: "Raw data from PostgreSQL loaded via Airbyte"
    columns:
      - name: symbol
        tests:
          - not_null
          # - custom_tests.price_positive
      - name: Open
        tests:
          - not_null
          # - custom_tests.price_positive
      - name: Close
        tests:
          - not_null
          # - custom_tests.price_positive
      - name: Volume
        tests:
          - not_null
          # - custom_tests.price_positive
# tests:
#   - name: price_positive
#     description: "Ensure that price fields are positive"
#     sql: |
#       SELECT *
#       FROM {{ model }}
#       WHERE "Open" <= 0 OR "Close" <= 0

#   - name: volume_positive
#     description: "Ensure that volume is positive"
#     sql: |
#       SELECT *
#       FROM {{ model }}
#       WHERE "Volume" <= 0
